name: your-workflow-name
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          #python train.py
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.DVC}}
        run: |
          # Post reports as comments in GitHub PRs
          dvc pull data/data.csv --run-cache
          echo "### data pulled"
          #cat results.txt >> report.md
          cml-send-comment report.md